using Pkg
pkg"add DifferentialEquations"
pkg"add Distributed"
pkg"add Statistics"
pkg"add BenchmarkTools"
pkg"add StaticArrays"
pkg"add FFTW"
pkg"add DSP"
pkg"add Interpolations"
pkg"add SpecialFunctions"
pkg"add IterTools"
pkg"add JLD2"
pkg"add Statistics"
pkg"add SpecialFunctions"
pkg"add LinearAlgebra"
pkg"add Rotations"
pkg"add StaticArrays"
pkg"add MAT"
pkg"add Dates"
pkg"add IJulia"
pkg"add Revise"
pkg"add Parameters"
pkg"add Plots"
pkg"add Optim"

pkg"precompile"
